name: Update README with Stats

on:
  schedule:
    - cron: '0 */12 * * *' 
  workflow_dispatch:       

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Stats with token
        uses: anuraghazra/github-readme-stats@master
        with:
          token: ${{ secrets.GH_TOKEN }}
          username: Dyckson
          show_icons: true
          theme: radical
          layout: compact

      - name: Commit & Push if README changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update README with latest stats" || echo "No changes to commit"
          git push
